### ISSUE TITLE
Thread 41 "rtpjitterbuffer" received signal SIGSEGV, Segmentation fault.

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#159]
When trying to join conference audio, many times the call just gets disconnected, and sometimes with a segfault.

Backtrace:
```
Starting program: /usr/bin/pidgin.orig 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe0be4700 (LWP 15972)]
[New Thread 0x7fffdbfff700 (LWP 15973)]
[New Thread 0x7fffdb7fe700 (LWP 15974)]
[New Thread 0x7fffc42be700 (LWP 15975)]
[New Thread 0x7fffc3abd700 (LWP 15976)]
[New Thread 0x7fffc3066700 (LWP 15977)]
[New Thread 0x7fffc2759700 (LWP 15978)]
[New Thread 0x7fffb0f90700 (LWP 15979)]
[New Thread 0x7fff6bffd700 (LWP 15980)]
[New Thread 0x7fff6b7fc700 (LWP 15981)]
[New Thread 0x7fff6affb700 (LWP 15982)]
[New Thread 0x7fff6a7fa700 (LWP 15991)]
[New Thread 0x7fff69ff9700 (LWP 15992)]
[New Thread 0x7fff695f5700 (LWP 15993)]
[Thread 0x7fff695f5700 (LWP 15993) exited]
[Thread 0x7fff6a7fa700 (LWP 15991) exited]
[New Thread 0x7fff6a7fa700 (LWP 16006)]
[Thread 0x7fff69ff9700 (LWP 15992) exited]
[New Thread 0x7fff69ff9700 (LWP 16013)]
[New Thread 0x7fff695f5700 (LWP 16014)]
[Thread 0x7fff695f5700 (LWP 16014) exited]
[Thread 0x7fff69ff9700 (LWP 16013) exited]
[Thread 0x7fff6a7fa700 (LWP 16006) exited]
[New Thread 0x7fff6a7fa700 (LWP 16046)]
[New Thread 0x7fff69ff9700 (LWP 16068)]
[New Thread 0x7fff695f5700 (LWP 16069)]
[New Thread 0x7fff2ee13700 (LWP 16070)]
[New Thread 0x7fff2e612700 (LWP 16071)]
[New Thread 0x7fff2dc0a700 (LWP 16072)]
[New Thread 0x7fff2d409700 (LWP 16073)]
[New Thread 0x7fff2cc08700 (LWP 16074)]
[New Thread 0x7fff17fff700 (LWP 16076)]
[New Thread 0x7fff177fe700 (LWP 16077)]
[Thread 0x7fff2e612700 (LWP 16071) exited]
[New Thread 0x7fff2e612700 (LWP 16078)]
[New Thread 0x7fff16ffd700 (LWP 16079)]
[Thread 0x7fff69ff9700 (LWP 16068) exited]
[Thread 0x7fff2e612700 (LWP 16078) exited]
[Thread 0x7fff16ffd700 (LWP 16079) exited]
[Thread 0x7fff2ee13700 (LWP 16070) exited]
[Thread 0x7fff695f5700 (LWP 16069) exited]
[Thread 0x7fff2cc08700 (LWP 16074) exited]
[Thread 0x7fff2d409700 (LWP 16073) exited]
[Thread 0x7fff177fe700 (LWP 16077) exited]
[Thread 0x7fff17fff700 (LWP 16076) exited]
[Thread 0x7fff6a7fa700 (LWP 16046) exited]
[New Thread 0x7fff6a7fa700 (LWP 16082)]
[New Thread 0x7fff17fff700 (LWP 16083)]
[New Thread 0x7fff177fe700 (LWP 16084)]
[New Thread 0x7fff2d409700 (LWP 16085)]
[New Thread 0x7fff69ff9700 (LWP 16086)]
[New Thread 0x7fff695f5700 (LWP 16087)]
[New Thread 0x7fff2ee13700 (LWP 16088)]
[New Thread 0x7fff2e612700 (LWP 16089)]
[New Thread 0x7fff2cc08700 (LWP 16090)]
[New Thread 0x7fff16ffd700 (LWP 16091)]
[New Thread 0x7fff167fc700 (LWP 16092)]

(Pidgin:15971): GStreamer-CRITICAL **: gst_bin_remove: assertion 'GST_IS_BIN (bin)' failed

(Pidgin:15971): GStreamer-CRITICAL **: gst_bin_remove: assertion 'GST_IS_BIN (bin)' failed

(Pidgin:15971): GStreamer-CRITICAL **: gst_bin_remove: assertion 'GST_IS_BIN (bin)' failed
[Thread 0x7fff69ff9700 (LWP 16086) exited]
[Thread 0x7fff17fff700 (LWP 16083) exited]
[Thread 0x7fff6a7fa700 (LWP 16082) exited]

Thread 41 "rtpjitterbuffer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff167fc700 (LWP 16092)]
0x00007ffff65fc49b in gst_bin_add () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
(gdb) bt
#0  0x00007ffff65fc49b in gst_bin_add () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#1  0x00007ffff1c5c8ae in src_pad_added_cb (fsstream=<optimized out>, srcpad=0x7fff4c091b20, codec=<optimized out>, stream=0x1b80bf0)
    at /build/pidgin-6Sf3gz/pidgin-3.0.0~collab/./libpurple/media/backend-fs2.c:1940
#2  0x00007fffe8761e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#3  0x00007fffe87618ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#4  0x00007ffff2299cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x00007ffff22991d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x00007ffff22b39a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007ffff22b408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007fffe8761e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#9  0x00007fffe87618ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
#10 0x00007ffff2299cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#11 0x00007ffff22991d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#12 0x00007ffff22b39a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007ffff22b408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#14 0x00007fff4bdd8ac2 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libfsrtpconference.so
#15 0x00007fff4bdd92b3 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libfsrtpconference.so
#16 0x00007ffff663226b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#17 0x00007ffff7800904 in g_hook_list_marshal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007ffff6630a9b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#19 0x00007ffff66336d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#20 0x00007ffff6633be0 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#21 0x00007ffff663188f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#22 0x00007ffff663d924 in gst_pad_push_event () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#23 0x00007ffff663da9b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#24 0x00007ffff66394de in gst_pad_forward () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#25 0x00007ffff6639633 in gst_pad_event_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#26 0x00007ffff6633367 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#27 0x00007ffff663379e in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#28 0x00007ffff6633be0 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#29 0x00007ffff663188f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#30 0x00007ffff6633fe1 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#31 0x00007ffff663c543 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#32 0x00007fff4bb8b832 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
#33 0x00007ffff663459f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#34 0x00007ffff663c543 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#35 0x00007fff4bb85aa0 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
#36 0x00007fff4bb86aca in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
#37 0x00007ffff6666f31 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
#38 0x00007ffff783754e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#39 0x00007ffff7836bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#40 0x00007ffff75b06ba in start_thread (arg=0x7fff167fc700) at pthread_create.c:333
#41 0x00007ffff72e63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by xnandersson** [comment]
````
(gdb) bt full
#0  0x00007ffff65fc49b in gst_bin_add () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#1  0x00007ffff1c5c8ae in src_pad_added_cb (fsstream=<optimized out>, srcpad=<error reading variable: Cannot access memory at address 0x7fff167fa388>, 
    codec=<optimized out>, stream=<error reading variable: Cannot access memory at address 0x7fff167fa378>)
    at /build/pidgin-6Sf3gz/pidgin-3.0.0~collab/./libpurple/media/backend-fs2.c:1940
        output_volume = <optimized out>
        sink = <error reading variable sink (Cannot access memory at address 0x7fff167fa390)>
        priv = <error reading variable priv (Cannot access memory at address 0x7fff167fa380)>
        sinkpad = <optimized out>
        __func__ = <error reading variable __func__ (Cannot access memory at address 0x7ffff1ce50b0)>
#2  0x00007fffe8761e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#3  0x00007fffe87618ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#4  0x00007ffff2299cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#5  0x00007ffff22991d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#6  0x00007ffff22b39a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#7  0x00007ffff22b408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#8  0x00007fffe8761e40 in ffi_call_unix64 () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#9  0x00007fffe87618ab in ffi_call () from /usr/lib/x86_64-linux-gnu/libffi.so.6
No symbol table info available.
#10 0x00007ffff2299cf5 in g_cclosure_marshal_generic_va () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#11 0x00007ffff22991d4 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#12 0x00007ffff22b39a6 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#13 0x00007ffff22b408f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
#14 0x00007fff4bdd8ac2 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libfsrtpconference.so
No symbol table info available.
#15 0x00007fff4bdd92b3 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libfsrtpconference.so
No symbol table info available.
#16 0x00007ffff663226b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#17 0x00007ffff7800904 in g_hook_list_marshal () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#18 0x00007ffff6630a9b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#19 0x00007ffff66336d6 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#20 0x00007ffff6633be0 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#21 0x00007ffff663188f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#22 0x00007ffff663d924 in gst_pad_push_event () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#23 0x00007ffff663da9b in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#24 0x00007ffff66394de in gst_pad_forward () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#25 0x00007ffff6639633 in gst_pad_event_default () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#26 0x00007ffff6633367 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#27 0x00007ffff663379e in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#28 0x00007ffff6633be0 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#29 0x00007ffff663188f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#30 0x00007ffff6633fe1 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#31 0x00007ffff663c543 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#32 0x00007fff4bb8b832 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
No symbol table info available.
#33 0x00007ffff663459f in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#34 0x00007ffff663c543 in gst_pad_push () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#35 0x00007fff4bb85aa0 in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
No symbol table info available.
#36 0x00007fff4bb86aca in ?? () from /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstrtpmanager.so
No symbol table info available.
#37 0x00007ffff6666f31 in ?? () from /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0
No symbol table info available.
#38 0x00007ffff783754e in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#39 0x00007ffff7836bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#40 0x00007ffff75b06ba in start_thread (arg=<error reading variable: Cannot access memory at address 0x7fff167fbbe8>) at pthread_create.c:333
        __res = <optimized out>
        pd = <error reading variable pd (Cannot access memory at address 0x7fff167fbbe8)>
        now = <optimized out>
        unwind_buf = <error reading variable unwind_buf (Cannot access memory at address 0x7fff167fbbf0)>
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = <error reading variable __PRETTY_FUNCTION__ (Cannot access memory at address 0x7ffff75bbc90)>
#41 0x00007ffff72e63dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb) 
```

**Comment by xnandersson** [comment]
```
ii  gstreamer1.0-nice:amd64                     0.1.14~sipe-0+201701270901~ubuntu16.04.1                            amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-5:amd64                    0.2.8+sipe+collab-1+201701011925~ubuntu16.04.1                      amd64        Audio/Video communications framework: core library
ii  libfreerdp-cache1.1:amd64                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-client2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                    1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                     1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                  1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-plugins-standard:amd64           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-primitives1.1:amd64              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-server2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp-utils1.1:amd64                   1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2                        amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp2:amd64                           2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libnice10:amd64                             0.1.14~sipe-0+201701270901~ubuntu16.04.1                            amd64        ICE library (shared library)
ii  libwinpr-tools2:amd64                       2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2:amd64                             2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 amd64        Windows Portable Runtime library
ii  pidgin                                      1:3.0.0~collab-1+201706131018~ubuntu16.04.1                         amd64        graphical multi-protocol instant messaging client
ii  pidgin-data                                 1:3.0.0~collab-1+201706131018~ubuntu16.04.1                         all          multi-protocol instant messaging client - data files
ii  pidgin-dbg                                  1:3.0.0~collab-1+201706131018~ubuntu16.04.1                         amd64        Debugging symbols for Pidgin
ii  pidgin-sipe                                 1.22.1+sipe-0+201709221532~ubuntu16.04.1                            amd64        Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                             1.22.1+sipe-0+201709221532~ubuntu16.04.1                            amd64        Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)
ii  remmina                                     1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1                       amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                              1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1                       all          common files for remmina remote desktop client
ii  remmina-plugin-nx                           1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1                       amd64        NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                          1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1                       amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc                          1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1                       amd64        VNC plugin for remmina remote desktop client
```
