### ISSUE TITLE
pidgin-sipe crash when quitting pidgin

### ISSUE THREAD

**Issue by gy-lehel** [tieto/sipe#20]
(gdb) where
#0  0x00007f56bde62a53 in gplugin_plugin_get_type () at /build/gplugin-tzz2ep/gplugin-0.0.19+5~ubuntu14.04.1/gplugin/gplugin-plugin.c:269
#1  0x00007f56bde62cc9 in gplugin_plugin_get_state (plugin=0x564ce1cc90c0) at /build/gplugin-tzz2ep/gplugin-0.0.19+5~ubuntu14.04.1/gplugin/gplugin-plugin.c:351
#2  0x00007f56b949f53e in purple_plugin_is_loaded (plugin=<optimized out>) at plugins.c:251
#3  0x00007f56b949f6a5 in purple_plugin_unload (plugin=0x564ce1cc90c0, error=error@entry=0x0) at plugins.c:222
#4  0x00007f56b94a0ffa in purple_plugins_uninit () at plugins.c:1146
#5  0x00007f56b947b595 in purple_core_quit () at core.c:286
#6  0x00007f56b9aca3b8 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x00007f56b9adbd3d in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x00007f56b9ae3a29 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x00007f56b9ae3ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#10 0x00007f56bac16a2c in gtk_widget_activate () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007f56bab0a736 in gtk_menu_shell_activate_item () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#12 0x00007f56bab0aa66 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#13 0x00007f56baaeed3e in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#14 0x00007f56b9aca5e7 in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#15 0x00007f56b9ae3088 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#16 0x00007f56b9ae3ce2 in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#17 0x00007f56bac17974 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#18 0x00007f56baaed08c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#19 0x00007f56baaee91a in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007f56ba6f2c22 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#21 0x00007f56be8a6e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#22 0x00007f56be8a7048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007f56be8a730a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007f56baaede25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#25 0x00007f56bec2e0e5 in pidgin_start (argc=1, argv=0x7ffe9bcd0708) at libpidgin.c:850
#26 0x00007f56be29cec5 in __libc_start_main (main=0x564ce03d0960 <main>, argc=1, argv=0x7ffe9bcd0708, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe9bcd06f8) at libc-start.c:287
#27 0x0000564ce03d09de in _start ()

**Comment by gy-lehel** [comment]
Confirmed as fixed in latest package 1.20.1+collab-201602251145+3174~ubuntu14.04.1
