### ISSUE TITLE
Error during File Transfer Pidgin 3 -> Pidgin 3

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#4]
Back Trace:

```
[New Thread 0x7fff3e7fc700 (LWP 6625)]

Program received signal SIGSEGV, Segmentation fault.
ft_end (xfer=0x7fff34002370) at purple-ft.c:268
268 purple-ft.c: No such file or directory.
(gdb) 
(gdb) bt
#0  ft_end (xfer=0x7fff34002370) at purple-ft.c:268
#1  0x00007ffff266250a in purple_xfer_end (xfer=0x7fff34002370) at xfer.c:1669
#2  0x00007fffd2ce3549 in end_transfer_cb (data=<optimized out>)
    at purple-ft.c:135
#3  0x00007ffff7814703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff7813ce5 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff7814048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff781430a in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff3f7afe5 in gtk_main ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#8  0x00007ffff7b989c0 in pidgin_start (argc=1, argv=0x7fffffffde88)
    at libpidgin.c:869
#9  0x00007ffff7208ec5 in __libc_start_main (main=0x555555554960 <main>, 
    argc=1, argv=0x7fffffffde88, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffde78) at libc-start.c:287
#10 0x00005555555549de in _start ()
(gdb)
```

**Comment by xhaakon** [comment]
Should be fixed in current version. Closing.
