### ISSUE TITLE
Infinite cycle, and freeze during normal operation

### ISSUE THREAD

**Issue by gy-lehel** [tieto/sipe#41]
There is an infinite cycle, and freezeright after RA disconnect and re-connect.

Installed:

```
ii  pidgin                                                1:3.0.0~collab-0.20603+20160309 amd64                           graphical multi-protocol instant messaging client for X
ii  pidgin-data                                           1:3.0.0~collab-0.20603+20160309 all                             multi-protocol instant messaging client - data files
ii  pidgin-dbg                                            1:3.0.0~collab-0.20603+20160309 amd64                           Debugging symbols for Pidgin
un  pidgin-facebookchat                                   <none>                          <none>                          (no description available)
ii  pidgin-gnome-keyring                                  2.0~trusty-1                    amd64                           integrates pidgin (and libpurple) with the system keyring
ii  pidgin-otr                                            4.0.0-2                         amd64                           Off-the-Record Messaging plugin for Pidgin
rc  pidgin-ppa                                            0.0.9                           all                             Pidgin PPA
ii  pidgin-sipe                                           1.20.1+collab-201603091047+3179 amd64                           Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                                       1.20.1+collab-201603091047+3179 amd64                           Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)
```

Backtrace:

```
#0  0x00007fb59354b95b in __libc_send (fd=34, buf=0x555ef569e140, n=13449, flags=-1823164069) at ../sysdeps/unix/sysv/linux/x86_64/send.c:31
#1  0x00007fb584d4a876 in ?? () from /usr/lib/x86_64-linux-gnu/libnspr4.so
#2  0x00007fb57d2690bc in ?? () from /usr/lib/x86_64-linux-gnu/libssl3.so
#3  0x00007fb57d26e18e in ?? () from /usr/lib/x86_64-linux-gnu/libssl3.so
#4  0x00007fb57d26f590 in ?? () from /usr/lib/x86_64-linux-gnu/libssl3.so
#5  0x00007fb57d2733b8 in ?? () from /usr/lib/x86_64-linux-gnu/libssl3.so
#6  0x00007fb57d6c4295 in ssl_nss_write (gsc=0x22, data=0x555ef569e140, len=13449) at ssl-nss.c:615
#7  0x00007fb575b46bdd in transport_write (transport=transport@entry=0x555ef564f310) at purple-transport.c:368
#8  0x00007fb575b470f8 in sipe_backend_transport_flush (conn=0x555ef564f310) at purple-transport.c:430
#9  0x00007fb575b1af10 in sipe_core_deallocate (sipe_public=0x555ef55a8390) at sipe-core.c:435
#10 0x00007fb575b0966e in sipe_purple_close (gc=0x555ef55973a0) at purple-plugin-common.c:519
#11 0x00007fb58e377016 in purple_connection_finalize (object=0x555ef55973a0) at connection.c:789
#12 0x00007fb58e9cadba in g_object_unref () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x00007fb58e357ae8 in purple_account_disconnect (account=0x555ef3fa9a80) at account.c:385
#14 0x00007fb58e375dc5 in purple_connection_disconnect_cb (data=0x555ef3fa9a80) at connection.c:456
#15 0x00007fb5937a3703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007fb5937a2ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007fb5937a3048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x00007fb5937a330a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007fb58f9e9e25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#20 0x00007fb593b29eb5 in pidgin_start (argc=1, argv=0x7ffd24211928) at libpidgin.c:850
#21 0x00007fb593198ec5 in __libc_start_main (main=0x555ef2ab7960 <main>, argc=1, argv=0x7ffd24211928, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd24211918) at libc-start.c:287
#22 0x0000555ef2ab79de in _start ()
```

**Comment by xhaakon** [comment]
Merged with #54.
