### ISSUE TITLE
screen sharing does not work while video-call running

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#48]
1. Establish video-call
2. Share your desktop

gdb-stack-trace (pidgin.orig)

```
[17:02:25:270] [4371:4371] [INFO][com.freerdp.server.shadow.x11] - X11 Extensions: XFixes: 1 Xinerama: 1 XDamage: 0 XShm: 0
[17:02:25:275] [4371:4371] [INFO][com.freerdp.core.listener] - Listening on socket /run/user/1000/sipe/applicationsharing-4371-C562g1531a0E65i53EAmA721t54ABb3701x3F1Fx.
[New Thread 0x7ffed23dd700 (LWP 4621)]
[New Thread 0x7ffed1bdc700 (LWP 4622)]
[17:02:28:278] [4371:4621] [ERROR][com.freerdp.core.peer] - Failed to create new peer context
[17:02:28:279] [4371:4621] [ERROR][com.freerdp.core.listener] - PeerAccepted callback failed
```

gdb-stack-trace remmina: (It doesn't seem helpful but here it is)

```
(gdb) file remmina
Reading symbols from remmina...Reading symbols from /usr/lib/debug/.build-id/2b/89ae97eeea4bd695a3312d7ec8cc1385382e34.debug...done.
done.
(gdb) run
Starting program: /usr/bin/remmina
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdf3d1700 (LWP 3982)]
[New Thread 0x7fffdebd0700 (LWP 3983)]
[New Thread 0x7fffde3cf700 (LWP 3984)]
[New Thread 0x7fffc76ab700 (LWP 3985)]
[New Thread 0x7fffc6164700 (LWP 3986)]
[Thread 0x7fffc6164700 (LWP 3986) exited]
[Thread 0x7fffc76ab700 (LWP 3985) exited]

^C
Thread 1 "remmina" received signal SIGINT, Interrupt.
0x00007ffff27efe8d in poll () at ../sysdeps/unix/syscall-template.S:84
84    ../sysdeps/unix/syscall-template.S: No such file or directory.
(gdb) bt full
#0  0x00007ffff27efe8d in poll () at ../sysdeps/unix/syscall-template.S:84
No locals.
#1  0x00007ffff6f0631c in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff6f066a2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff76b96f5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#4  0x0000000000417744 in main (argc=1, argv=0x7fffffffde78) at /build/remmina-F2esEk/remmina-1.1.2/remmina/src/remmina.c:303
        app = 0x6ff940
        app_class = <optimized out>
        status = 0
(gdb) 
```

...the crash resulted in some report from apport. Attaching it as inline picture.

![crash-remmina](https://cloud.githubusercontent.com/assets/7423586/14609485/4dca328e-058a-11e6-8ffa-237631fe24be.png)

Versions:

```
nandersson@nandersson-ThinkPad-X1-Carbon-2nd:~$ dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp
ii  gstreamer0.10-nice:amd64                             0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                              0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-bad:amd64                       1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64          1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer videoparsers plugin from the "bad" set
ii  libfarstream-0.1-0:amd64                             0.1.2-3ubuntu1                                                    amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-5:amd64                             0.2.8+sipe+collab-0.3010+201604142223~ubuntu16.04.1               amd64        Audio/Video communications framework: core library
ii  libfreerdp-cache1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-client2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201603221017~23~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                         1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-primitives1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-server2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201603221017~23~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201603221017~23~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp-utils1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp2:amd64                                    2.0.0~git20160317.1.75ae3f5+dfsg1-0~201603221017~23~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libgstreamer-plugins-bad1.0-0:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer development files for libraries from the "bad" set
ii  libnice-dev                                          0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (development files)
ii  libnice10:amd64                                      0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (shared library)
ii  libtelepathy-farstream3:amd64                        0.6.2-1build1                                                     amd64        Glue library between telepathy and farstream
ii  pidgin                                               1:3.0.0~collab-0.20620+201604150417~ubuntu16.04.1                 amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                          1:3.0.0~collab-0.20620+201604150417~ubuntu16.04.1                 all          multi-protocol instant messaging client - data files
ii  pidgin-dbg                                           1:3.0.0~collab-0.20620+201604150417~ubuntu16.04.1                 amd64        Debugging symbols for Pidgin
ii  pidgin-sipe                                          1.20.1+collab-201604181347+3203~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                                      1.20.1+collab-201604181347+3203~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)
ii  remmina                                              1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                       1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    all          common files for remmina remote desktop client
ii  remmina-dbg                                          1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        remote desktop client - debug pakcage
ii  remmina-plugin-gnome                                 1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        GNOME plugin for remmina remote desktop client
ii  remmina-plugin-nx                                    1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                                   1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-telepathy                             1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        Telepathy plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                   1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        VNC plugin for remmina remote desktop client
ii  remmina-plugin-xdmcp                                 1.1.2-sipe+201604140832+next+852~ubuntu16.04.1                    amd64        XDMCP plugin for remmina remote desktop client
```

**Comment by xhaakon** [comment]
> 1. Share your desktop

Since you attached remmina log I presume you wanted to write "view remote desktop"?

I tried this and can do both video and appshare simultaneously on 16.04, so I think this crash isn't related to the presence of the video stream. Can you get some logs while you're viewing a desktop without video? Preferably with libnice messages included.

**Comment by xhaakon** [comment]
This crash looks pretty similar to #59.

**Comment by xhaakon** [comment]
I think there's no meaningful way to distinguish this from #59. Merged as duplicate.
