### ISSUE TITLE
Segfault in g_cancellable_cancel()

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#60]
User supplied back-trace. Not sure if this is reproducible:

```
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/pidgin.orig
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

** (Pidgin:14146): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-amhd2sCB4b: Connection refused
[New Thread 0x7fffe3842700 (LWP 14147)]
[New Thread 0x7fffe2591700 (LWP 14148)]
[New Thread 0x7fffbd8ae700 (LWP 14157)]
[New Thread 0x7fff7cfa9700 (LWP 14158)]
[New Thread 0x7fff7097c700 (LWP 14163)]
[New Thread 0x7fff7017b700 (LWP 14164)]
[New Thread 0x7fff6f97a700 (LWP 14165)]
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.14.04.2)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

...output cut for brevity...

[Thread 0x7fff34a47700 (LWP 31119) exited]

(process:31260): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
[New Thread 0x7fff34a47700 (LWP 31488)]
[Thread 0x7fff34a47700 (LWP 31488) exited]
[New Thread 0x7fff34a47700 (LWP 31644)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff30b0cc2 in g_cancellable_cancel () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
(gdb)
(gdb)
(gdb)
(gdb) bt full
#0  0x00007ffff30b0cc2 in g_cancellable_cancel () from /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
No symbol table info available.
#1  0x00007ffff7812703 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff7811ce5 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#3  0x00007ffff7812048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#4  0x00007ffff781230a in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#5  0x00007ffff3a54e25 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
#6  0x00007ffff7b98445 in pidgin_start (argc=1, argv=0x7fffffffde78) at libpidgin.c:850
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = 0
        opt_si = 1
        opt_config_dir_arg = 0x0
        opt_login_arg = <optimized out>
        opt_session_arg = 0x0
        search_path = <optimized out>
        provider = <optimized out>
        screen = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {82950, 0 <repeats 15 times>}}
        errmsg = "\000\275\377\377\377\177\000\000\070\233\372\367\377\177\000\000p\336\377\377\377\177\000\000@\003\000\000\000\000\000\000\177ELF\002\001\001\000\000\000\000\000\000\000\000\000\003\000>\000\001\000\000\000\240\t\000\000\000\000\000\000@\000\000\000\000\000\000\000pA\000\000\000\000\000\000\000\000\000\000@\000\070\000\a\000@\000\032\000\031\000\001\000\000\000\005", '\000' <repeats 27 times>, "\\0\000\000\000\000\000\000\\0\000\000\000\000\000\000\000\000 \000\000\000\000\000\001\000\000\000\006\000\000\000\350=\000\000\000\000\000\000\350= \000\000\000\000\000\350= \000\000\000\000\000\200\002\000\000\000\000\000\000\210\002\000\000\000\000\000\000\000\000"...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        error = 0x5555557c6970
        segfault_message_tmp = <optimized out>
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        debug_colored = <optimized out>
        active_accounts = <optimized out>
        st = {st_dev = 64513, st_ino = 4331655, st_nlink = 2, st_mode = 16832, st_uid = 51810, st_gid = 6008, __pad0 = 0, st_rdev = 0, st_size = 4096, st_blksize = 4096, st_blocks = 8, st_atim = {tv_sec = 1427375207, tv_nsec = 573656326}, st_mtim = {tv_sec = 1452498761, tv_nsec = 122613364}, st_ctim = {tv_sec = 1452498761, tv_nsec = 122613364},
          __glibc_reserved = {0, 0, 0}}
        long_options = {{name = 0x7ffff7badd28 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x7ffff7b9b1c8 "debug", has_arg = 2, flag = 0x0, val = 100}, {name = 0x7ffff7bb244a "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x7ffff7b9cdd6 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x7ffff7bb232f "login", has_arg = 2, flag = 0x0,
            val = 108}, {name = 0x7ffff7bb2457 "multiple", has_arg = 0, flag = 0x0, val = 109}, {name = 0x7ffff7bb2460 "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x7ffff7badd1e "session", has_arg = 1, flag = 0x0, val = 115}, {name = 0x7ffff7b9fddd "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x7ffff7badd31 "display", has_arg = 1,
            flag = 0x0, val = 68}, {name = 0x7ffff7ba9935 "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
#7  0x00007ffff7207f45 in __libc_start_main (main=0x555555554960 <main>, argc=1, argv=0x7fffffffde78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde68) at libc-start.c:287
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -4888246871239431080, 93824992233909, 140737488346736, 0, 0, 4888246870089657432, 4888265000262691928}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffde88, 0x7ffff7ffe1c8}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8568}}}
        not_first_call = <optimized out>
#8  0x00005555555549de in _start ()
No symbol table info available.
(gdb)
```

**Comment by xhaakon** [comment]
I've seen this today and I think I know where it is coming from.

**Comment by xhaakon** [comment]
Please update to this Pidgin when it becomes available in the PPA:

```
pidgin - 1:3.0.0~collab-0.20636+201605030932~ubuntu16.04.1
pidgin - 1:3.0.0~collab-0.20636+201605030932~ubuntu15.10.1
pidgin - 1:3.0.0~collab-0.20636+201605030933~ubuntu15.04.1
pidgin - 1:3.0.0~collab-0.20636+201605030933~ubuntu14.04.1
```

**Comment by tmuehlhoff** [comment]
I reported this problem: However just after reporting I updated and stepped over the same problem again. 1:3.0.0~collab-0.20635+201605030724~ubuntu14.04.1
Ill update to 0932/0933 now.

**Comment by xhaakon** [comment]
@tmuehlhoff  201605030724 doesn't include the fix; you need something more recent.

Btw. are you logged in through a poor network connection or switching between networks frequently (e.g. roaming over a building with a laptop)? I'm just surprised how often your Pidgin gets disconnected from the server...

**Comment by tmuehlhoff** [comment]
How often is it ? should be less than once per hour or so...

**Comment by xhaakon** [comment]
Don't know the exact figure - these crashes are happening while Pidgin is shutting down the connection (it started after some upstream refactoring about a week ago).

I was just curious it there's a reason for you disconnecting so often or if perhaps there isn't any technical problem that would cause those shutdowns. If you're logging off intentionally about every hour, it all makes sense now.

I usually work from a single place and I see disconnects so rarely I didn't even register any segfaults before you started reporting bugs.

**Comment by tmuehlhoff** [comment]
wouldnt call it "logging off" rather switching from LAN to Wifi or Wifi to Wifi with possible coverage gaps.
Is this may match what you see from the trace then it's expected.

**Comment by xhaakon** [comment]
Two weeks since the fix release have passed without any further reports, so I consider this issue fixed and am closing it.
