### ISSUE TITLE
Segfault while pasting in IM

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#61]
Reproducible: Not always. Happens sometimes.

Back Trace:

```
Thread 1 "pidgin.orig" received signal SIGSEGV, Segmentation fault.
WebCore::HTMLElement::parseAttribute (this=0x5555568d4300, name=..., value=...) at ../Source/WebCore/html/HTMLElement.cpp:349
349 ../Source/WebCore/html/HTMLElement.cpp: No such file or directory.
(gdb) bt
#0  WebCore::HTMLElement::parseAttribute (this=0x5555568d4300, name=..., value=...) at ../Source/WebCore/html/HTMLElement.cpp:349
#1  0x00007ffff45b06d8 in WebCore::Element::attributeChanged (this=0x5555568d4300, name=..., oldValue=..., newValue=...) at ../Source/WebCore/dom/Element.cpp:1097
#2  0x00007ffff45afca0 in WebCore::Element::didModifyAttribute (this=this@entry=0x5555568d4300, name=..., oldValue=..., newValue=...) at ../Source/WebCore/dom/Element.cpp:2851
#3  0x00007ffff45b6eed in WebCore::Element::setAttributeInternal (this=0x5555568d4300, index=<optimized out>, name=..., newValue=..., inSynchronizationOfLazyAttribute=<optimized out>) at ../Source/WebCore/dom/Element.cpp:1075
#4  0x00007ffff461d609 in WebCore::CompositeEditCommand::applyCommandToComposite (this=this@entry=0x7fff63f586c0, prpCommand=...) at ../Source/WebCore/editing/CompositeEditCommand.cpp:278
#5  0x00007ffff4622112 in WebCore::CompositeEditCommand::setNodeAttribute (this=this@entry=0x7fff63f586c0, element=..., attribute=..., value=...) at ../Source/WebCore/editing/CompositeEditCommand.cpp:664
#6  0x00007ffff4696d4f in WebCore::ReplaceSelectionCommand::removeRedundantStylesAndKeepStyleSpanInline (this=this@entry=0x7fff63f586c0, insertedNodes=...) at ../Source/WebCore/editing/ReplaceSelectionCommand.cpp:525
#7  0x00007ffff469988d in WebCore::ReplaceSelectionCommand::doApply (this=0x7fff63f586c0) at ../Source/WebCore/editing/ReplaceSelectionCommand.cpp:1151
#8  0x00007ffff461cba9 in WebCore::CompositeEditCommand::apply (this=0x7fff63f586c0) at ../Source/WebCore/editing/CompositeEditCommand.cpp:227
#9  0x00007ffff46478fb in WebCore::Editor::replaceSelectionWithFragment (this=0x5555566cf7b0, fragment=..., selectReplacement=<optimized out>, smartReplace=<optimized out>, matchStyle=<optimized out>) at ../Source/WebCore/editing/Editor.cpp:611
#10 0x00007ffff464d3f9 in WebCore::Editor::handleTextEvent (this=0x5555566cf7b0, event=event@entry=0x7fff63f48630) at ../Source/WebCore/editing/Editor.cpp:268
#11 0x00007ffff49b3beb in WebCore::EventHandler::defaultTextInputEventHandler (this=<optimized out>, event=event@entry=0x7fff63f48630) at ../Source/WebCore/page/EventHandler.cpp:3382
#12 0x00007ffff45d7609 in WebCore::Node::defaultEventHandler (this=0x555555c10290, event=0x7fff63f48630) at ../Source/WebCore/dom/Node.cpp:2118
#13 0x00007ffff45bae58 in WebCore::callDefaultEventHandlersInTheBubblingOrder (path=..., event=...) at ../Source/WebCore/dom/EventDispatcher.cpp:239
#14 WebCore::EventDispatcher::dispatchEvent (origin=0x555555c10290, prpEvent=...) at ../Source/WebCore/dom/EventDispatcher.cpp:346
#15 0x00007ffff45d3a15 in WebCore::Node::dispatchEvent (this=0x555555c10290, event=...) at ../Source/WebCore/dom/Node.cpp:2037
#16 0x00007ffff45bf0b1 in WebCore::EventTarget::dispatchEvent (this=this@entry=0x555555c10290, event=..., ec=@0x7fffffffa5e0: 0) at ../Source/WebCore/dom/EventTarget.cpp:152
#17 0x00007ffff46505df in WebCore::Editor::pasteAsFragment (this=this@entry=0x5555566cf7b0, pastingFragment=..., smartReplace=<optimized out>, matchStyle=matchStyle@entry=false) at ../Source/WebCore/editing/Editor.cpp:535
#18 0x00007ffff465079f in WebCore::Editor::pasteWithPasteboard (this=this@entry=0x5555566cf7b0, pasteboard=pasteboard@entry=0x7fff63f80070, allowPlainText=allowPlainText@entry=true) at ../Source/WebCore/editing/Editor.cpp:576
#19 0x00007ffff4650948 in WebCore::Editor::paste (this=0x5555566cf7b0, pasteboard=...) at ../Source/WebCore/editing/Editor.cpp:1346
#20 0x00007ffff4650990 in WebCore::Editor::paste (this=0x5555566cf7b0) at ../Source/WebCore/editing/Editor.cpp:1333
#21 0x00007ffff463d8db in WebCore::executePaste (frame=..., source=<optimized out>) at ../Source/WebCore/editing/EditorCommand.cpp:926
#22 0x00007ffff4251ead in WebKit::EditorClient::executePendingEditorCommands (this=this@entry=0x555556f460f0, frame=frame@entry=0x7fff63f4a900, allowTextInsertion=allowTextInsertion@entry=false)
    at ../Source/WebKit/gtk/WebCoreSupport/EditorClientGtk.cpp:401
#23 0x00007ffff425228d in WebKit::EditorClient::handleKeyboardEvent (this=0x555556f460f0, event=0x7fff63f79e88) at ../Source/WebKit/gtk/WebCoreSupport/EditorClientGtk.cpp:446
#24 0x00007ffff49b42c3 in WebCore::EventHandler::defaultKeyboardEventHandler (this=0x555556883450, event=event@entry=0x7fff63f79e88) at ../Source/WebCore/page/EventHandler.cpp:3074
#25 0x00007ffff45d7469 in WebCore::Node::defaultEventHandler (this=0x555555c10290, event=0x7fff63f79e88) at ../Source/WebCore/dom/Node.cpp:2104
#26 0x00007ffff45bae58 in WebCore::callDefaultEventHandlersInTheBubblingOrder (path=..., event=...) at ../Source/WebCore/dom/EventDispatcher.cpp:239
#27 WebCore::EventDispatcher::dispatchEvent (origin=0x555555c10290, prpEvent=...) at ../Source/WebCore/dom/EventDispatcher.cpp:346
#28 0x00007ffff45d3a15 in WebCore::Node::dispatchEvent (this=0x555555c10290, event=...) at ../Source/WebCore/dom/Node.cpp:2037
#29 0x00007ffff45bf0b1 in WebCore::EventTarget::dispatchEvent (this=this@entry=0x555555c10290, event=..., ec=@0x7fffffffabd0: 0) at ../Source/WebCore/dom/EventTarget.cpp:152
#30 0x00007ffff49b64c1 in WebCore::EventHandler::keyEvent (this=0x555556883450, initialKeyEvent=...) at ../Source/WebCore/page/EventHandler.cpp:2970
#31 0x00007ffff425b664 in WebKit::WebViewInputMethodFilter::sendSimpleKeyEvent (this=0x555555efd0b0, event=<optimized out>, simpleString=...) at ../Source/WebKit/gtk/WebCoreSupport/WebViewInputMethodFilter.cpp:60
#32 0x00007ffff4377597 in WebCore::GtkInputMethodFilter::filterKeyEvent (this=0x555555efd0b0, event=event@entry=0x555556f2e4c0) at ../Source/WebCore/platform/gtk/GtkInputMethodFilter.cpp:202
#33 0x00007ffff427c4ed in webkit_web_view_key_press_event (widget=0x555555efd2d0, event=0x555556f2e4c0) at ../Source/WebKit/gtk/webkit/webkitwebview.cpp:737
#34 0x00007ffff36f430c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#35 0x00007ffff2293eff in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#36 0x00007ffff22a656e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#37 0x00007ffff22ae7f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#38 0x00007ffff22af08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x00007ffff3831e5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#40 0x00007ffff3851eeb in gtk_window_propagate_key_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#41 0x00007ffff385536b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#42 0x00007ffff36f430c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#43 0x00007ffff2293fa5 in g_closure_invoke () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#44 0x00007ffff22a656e in ?? () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#45 0x00007ffff22ae7f9 in g_signal_emit_valist () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#46 0x00007ffff22af08f in g_signal_emit () from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#47 0x00007ffff3831e5c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#48 0x00007ffff36f1809 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#49 0x00007ffff36f351c in gtk_main_do_event () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#50 0x00007ffff3260ba2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
#51 0x00007ffff7809127 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#52 0x00007ffff7809380 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#53 0x00007ffff78096a2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#54 0x00007ffff36f26f5 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
#55 0x00007ffff7b93e94 in pidgin_start (argc=1, argv=0x7fffffffde68) at libpidgin.c:850
#56 0x00007ffff71f9830 in __libc_start_main (main=0x5555555548c0 <main>, argc=1, argv=0x7fffffffde68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde58) at ../csu/libc-start.c:291
#57 0x0000555555554949 in _start ()
(gdb) 
```

**Comment by xnandersson** [comment]
```
ii  gir1.2-gst-plugins-base-1.0                          1.8.0-1ubuntu1+sipe1                                              amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gstreamer0.10-nice:amd64                             0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-alsa:amd64                              1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-nice:amd64                              0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-bad:amd64                       1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64          1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-base:amd64                      1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base:i386                       1.8.0-1ubuntu1+sipe1                                              i386         GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base-apps                       1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer helper programs from the "base" set
ii  gstreamer1.0-x:amd64                                 1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugins for X11 and Pango
ii  libfarstream-0.1-0:amd64                             0.1.2-3ubuntu1                                                    amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-5:amd64                             0.2.8+sipe+collab-0.3010+201604211603~ubuntu16.04.1               amd64        Audio/Video communications framework: core library
ii  libfreerdp-cache1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-client2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                         1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-primitives1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-server2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp-utils1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp2:amd64                                    2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libgstreamer-plugins-bad1.0-0:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:amd64                 1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:i386                  1.8.0-1ubuntu1+sipe1                                              i386         GStreamer libraries from the "base" set
ii  libnice-dev                                          0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (development files)
ii  libnice10:amd64                                      0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (shared library)
ii  libtelepathy-farstream3:amd64                        0.6.2-1build1                                                     amd64        Glue library between telepathy and farstream
ii  pidgin                                               1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                          1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 all          multi-protocol instant messaging client - data files
ii  pidgin-dbg                                           1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 amd64        Debugging symbols for Pidgin
ii  pidgin-sipe                                          1.21.0+collab-201605031121+3210~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                                      1.21.0+collab-201605031121+3210~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)
ii  remmina                                              1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                       1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    all          common files for remmina remote desktop client
ii  remmina-dbg                                          1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        remote desktop client - debug pakcage
ii  remmina-plugin-gnome                                 1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        GNOME plugin for remmina remote desktop client
ii  remmina-plugin-nx                                    1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                                   1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-telepathy                             1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        Telepathy plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                   1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        VNC plugin for remmina remote desktop client
ii  remmina-plugin-xdmcp                                 1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        XDMCP plugin for remmina remote desktop client
nandersson@nandersson-ThinkPad-X1-Carbon-2nd:~$ 
```

**Comment by xnandersson** [comment]
ii  gir1.2-gst-plugins-base-1.0                          1.8.0-1ubuntu1+sipe1                                              amd64        Description: GObject introspection data for the GStreamer Plugins Base library
ii  gstreamer0.10-nice:amd64                             0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-alsa:amd64                              1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugin for ALSA
ii  gstreamer1.0-nice:amd64                              0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-bad:amd64                       1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64          1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-base:amd64                      1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base:i386                       1.8.0-1ubuntu1+sipe1                                              i386         GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base-apps                       1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer helper programs from the "base" set
ii  gstreamer1.0-x:amd64                                 1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer plugins for X11 and Pango
ii  libfarstream-0.1-0:amd64                             0.1.2-3ubuntu1                                                    amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-5:amd64                             0.2.8+sipe+collab-0.3010+201604211603~ubuntu16.04.1               amd64        Audio/Video communications framework: core library
ii  libfreerdp-cache1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-client2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                         1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                             1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                              1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                           1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-primitives1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-server2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow2:amd64                             2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp-utils1.1:amd64                            1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1                        amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp2:amd64                                    2.0.0~git20160317.1.75ae3f5+dfsg1-0~201604250541~24~ubuntu16.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libgstreamer-plugins-bad1.0-0:amd64                  1.8.0-1ubuntu1+sipe2                                              amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-base1.0-0:amd64                 1.8.0-1ubuntu1+sipe1                                              amd64        GStreamer libraries from the "base" set
ii  libgstreamer-plugins-base1.0-0:i386                  1.8.0-1ubuntu1+sipe1                                              i386         GStreamer libraries from the "base" set
ii  libnice-dev                                          0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (development files)
ii  libnice10:amd64                                      0.1.13+sipe+collab-201603090603+2222~ubuntu16.04.1                amd64        ICE library (shared library)
ii  libtelepathy-farstream3:amd64                        0.6.2-1build1                                                     amd64        Glue library between telepathy and farstream
ii  pidgin                                               1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                          1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 all          multi-protocol instant messaging client - data files
ii  pidgin-dbg                                           1:3.0.0~collab-0.20637+201605040931~ubuntu16.04.1                 amd64        Debugging symbols for Pidgin
ii  pidgin-sipe                                          1.21.0+collab-201605031121+3210~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                                      1.21.0+collab-201605031121+3210~ubuntu16.04.1                     amd64        Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)
ii  remmina                                              1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                       1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    all          common files for remmina remote desktop client
ii  remmina-dbg                                          1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        remote desktop client - debug pakcage
ii  remmina-plugin-gnome                                 1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        GNOME plugin for remmina remote desktop client
ii  remmina-plugin-nx                                    1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        NX plugin for remmina remote desktop client
ii  remmina-plugin-rdp                                   1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-telepathy                             1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        Telepathy plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                   1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        VNC plugin for remmina remote desktop client
ii  remmina-plugin-xdmcp                                 1.1.2-sipe+201605022146+next+852~ubuntu16.04.1                    amd64        XDMCP plugin for remmina remote desktop client
nandersson@nandersson-ThinkPad-X1-Carbon-2nd:~$
